"""Generates per-agent runtime index.py files."""

from __future__ import annotations

import json
from pathlib import Path

from dank_py.lib.config.models import AgentConfig


def build_agent_spec(agent: AgentConfig) -> dict:
    return {
        "name": agent.name,
        "id": agent.id,
        "entry": {
            "file": agent.entry.file,
            "symbol": agent.entry.symbol,
            "method": agent.entry.method,
            "call_type": agent.entry.call_type,
            "call_style": agent.entry.call_style,
        },
        "io": {
            "input": {
                "model": agent.io.input.model,
                "schema": agent.io.input.schema_,
            },
            "output": {
                "model": agent.io.output.model,
                "schema": agent.io.output.schema_,
            },
            "strict_output": agent.io.strict_output,
        },
    }


def render_index(agent: AgentConfig) -> str:
    spec_json = json.dumps(build_agent_spec(agent), indent=2)
    return f'''"""Generated by dank-py. Do not edit manually."""

from __future__ import annotations

import json

from dank_runtime.engine import resolve_callable, invoke

AGENT_SPEC = json.loads("""{spec_json}""")


def resolve_target(symbol):
    entry = AGENT_SPEC.get("entry", {{}})
    method = entry.get("method")
    call_type = entry.get("call_type", "auto")
    return resolve_callable(symbol, method=method, call_type=call_type)


async def invoke_target(callable_obj, payload):
    entry = AGENT_SPEC.get("entry", {{}})
    call_style = entry.get("call_style", "auto")
    return await invoke(callable_obj, payload, call_style=call_style)
'''


def write_generated_index(agent: AgentConfig, destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_index(agent), encoding="utf-8")
    return destination


def render_bundle_index(
    agents: list[AgentConfig],
    *,
    prompt_routing: str = "required",
    default_agent: str | None = None,
) -> str:
    bundle_payload = {
        "mode": "bundle",
        "prompt_routing": prompt_routing,
        "default_agent": default_agent,
        "agents": [build_agent_spec(agent) for agent in agents],
    }
    spec_json = json.dumps(bundle_payload, indent=2)
    return f'''"""Generated by dank-py. Do not edit manually."""

from __future__ import annotations

import json

from dank_runtime.engine import resolve_callable, invoke

BUNDLE_SPEC = json.loads("""{spec_json}""")


def resolve_target(symbol, agent_spec=None):
    spec = agent_spec or {{}}
    entry = spec.get("entry", {{}})
    method = entry.get("method")
    call_type = entry.get("call_type", "auto")
    return resolve_callable(symbol, method=method, call_type=call_type)


async def invoke_target(callable_obj, payload, agent_spec=None):
    spec = agent_spec or {{}}
    entry = spec.get("entry", {{}})
    call_style = entry.get("call_style", "auto")
    return await invoke(callable_obj, payload, call_style=call_style)
'''


def write_generated_bundle_index(
    agents: list[AgentConfig],
    destination: Path,
    *,
    prompt_routing: str = "required",
    default_agent: str | None = None,
) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_bundle_index(
            agents,
            prompt_routing=prompt_routing,
            default_agent=default_agent,
        ),
        encoding="utf-8",
    )
    return destination
